config/routes.rb
Rails.application.routes.draw do
  get 'users/index'
  devise_for :users 
  devise_scope :user do 
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end
  root to: "spots#index"
  resources :spots do
    resources :comments, only: [:create]
    collection do
      get 'search'
    end
  end
  resources :users, only: [:show]
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  with_options presence: true do
    validates :title
    validates :evaluation_id, numericality: { other_than: 0 }
    validates :review
  end

  belongs_to :user
  belongs_to :spot
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :evaluation
end

app/models/evaluation.rb
class Evaluation < ActiveHash::Base
  self.data = [
    { id: 0, name: '--' },
    { id: 1, name: '⭐️⭐️⭐️⭐️⭐️' },
    { id: 2, name: '⭐️⭐️⭐️⭐️' },
    { id: 3, name: '⭐️⭐️⭐️' },
    { id: 4, name: '⭐️⭐️' },
    { id: 5, name: '⭐️' },
  ]

  include ActiveHash::Associations
  has_many :comments
end

app/models/genre.rb
class Genre < ActiveHash::Base
  self.data = [
    { id: 0, name: '--' },
    { id: 1, name: 'ホテル' },
    { id: 2, name: 'ビジネスホテル' },
    { id: 3, name: '旅館' },
    { id: 4, name: '民宿' },
    { id: 5, name: 'コワーキングスペース' },
    { id: 6, name: 'その他' }
  ]

  include ActiveHash::Associations
  has_many :spots
end

app/models/place.rb
class Place < ActiveHash::Base
  self.data = [
               {id: 0, name: '--'}, {id: 1, name: '北海道'}, {id: 2, name: '青森県'}, 
               {id: 3, name: '岩手県'}, {id: 4, name: '宮城県'}, {id: 5, name: '秋田県'}, 
               {id: 6, name: '山形県'}, {id: 7, name: '福島県'}, {id: 8, name: '茨城県'}, 
               {id: 9, name: '栃木県'}, {id: 10, name: '群馬県'}, {id: 11, name: '埼玉県'}, 
               {id: 12, name: '千葉県'}, {id: 13, name: '東京都'}, {id: 14, name: '神奈川県'}, 
               {id: 15, name: '新潟県'}, {id: 16, name: '富山県'}, {id: 17, name: '石川県'}, 
               {id: 18, name: '福井県'}, {id: 19, name: '山梨県'}, {id: 20, name: '長野県'}, 
               {id: 21, name: '岐阜県'}, {id: 22, name: '静岡県'}, {id: 23, name: '愛知県'}, 
               {id: 24, name: '三重県'}, {id: 25, name: '滋賀県'}, {id: 26, name: '京都府'}, 
               {id: 27, name: '大阪府'}, {id: 28, name: '兵庫県'}, {id: 29, name: '奈良県'}, 
               {id: 30, name: '和歌山県'}, {id: 31, name: '鳥取県'}, {id: 32, name: '島根県'}, 
               {id: 33, name: '岡山県'}, {id: 34, name: '広島県'}, {id: 35, name: '山口県'}, 
               {id: 36, name: '徳島県'}, {id: 37, name: '香川県'}, {id: 38, name: '愛媛県'}, 
               {id: 39, name: '高知県'}, {id: 40, name: '福岡県'}, {id: 41, name: '佐賀県'}, 
               {id: 42, name: '長崎県'}, {id: 43, name: '熊本県'}, {id: 44, name: '大分県'}, 
               {id: 45, name: '宮崎県'}, {id: 46, name: '鹿児島県'}, {id: 47, name: '沖縄県'},
               {id: 48, name: 'その他(海外等)'}
              ]

  include ActiveHash::Associations
  has_many :spots
end

app/models/spot.rb
class Spot < ApplicationRecord
  with_options presence: true do
    validates :name
    validates :genre_id, numericality: { other_than: 0 }
    validates :place_id, numericality: { other_than: 0 }
    validates :explanation
    validates :wifi_id, numericality: { other_than: 0 }
    validates :image
  end

  belongs_to :user
  has_many :comments
  has_one_attached :image
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :genre
  belongs_to :place
  belongs_to :wifi

  def self.search(search)
    if search != ""
      Spot.where('name LIKE(?)', "%#{search}%")
    else
      Spot.all
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  with_options presence: true do
    VALID_PASSWORD_REGEX = /([0-9].*[a-zA-Z]|[a-zA-Z].*[0-9])/
    VALID_NAME_REGEX = /\A[ぁ-んァ-ン一-龥々+\z]/

    validates :nickname
    validates :age, numericality: { only_integer: true, greater_than_or_equal_to: 20 }
    validates :password, format: { with: VALID_PASSWORD_REGEX, message: "is invalid. Input Cannot be registered with a mixture of half-width alphanumeric characters " }
    with_options format: { with: VALID_NAME_REGEX, message: "is invalid. Input full-width characters." } do
      validates :last_name
      validates :first_name
    end
  end
  has_many :spots
  has_many :comments

  def self.guest
    find_or_create_by!(email: 'guest1234@gmail.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.password_confirmation = user.password
      user.nickname = 'ゲスト'
      user.last_name = 'ゲスト'
      user.first_name = 'ゲスト'
      user.age = 20
    end
  end
end

app/models/wifi.rb
class Wifi < ActiveHash::Base
  self.data = [
    { id: 0, name: '--' },
    { id: 1, name: 'wifi環境有り' },
    { id: 2, name: 'wifi環境無し' },
    { id: 3, name: 'その他' },
  ]

  include ActiveHash::Associations
  has_many :spots
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :basic_auth

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname, :last_name, :first_name, :age])
  end

  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV["BASIC_AUTH_USER"] && password == ENV["BASIC_AUTH_PASSWORD"]
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @spot = Spot.find(params[:spot_id])
    @comment = Comment.new(comment_params)
    if @comment.save
      redirect_to spot_path(@spot)
    else
      render :show
    end
  end

  private
  def comment_params
    params.require(:comment).permit(:title, :evaluation_id, :review).merge(user_id: current_user.id, spot_id: params[:spot_id])
  end
end

app/controllers/spots_controller.rb
class SpotsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_spot, only: [:show, :edit, :destroy]
  
  def index
    @spots = Spot.order("created_at DESC")
  end

  def new
    @spot = Spot.new
  end

  def create
    @spot = Spot.new(spot_params)
    if @spot.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @comment = Comment.new
    @comments = @spot.comments.includes(:user)
  end

  def edit
    unless @spot.user_id == current_user.id
      redirect_to root_path
    end
  end

  def update
    spot = Spot.find(params[:id])
    if spot.update(spot_params)
      redirect_to spot_path
    else
      render :edit
    end
  end

  def destroy
    if @spot.destroy
      redirect_to root_path
    else
      render :show
    end
  end

  def search
    @spots = Spot.search(params[:keyword])
  end

  private
  def spot_params
    params.require(:spot).permit(:name, :genre_id, :place_id, :explanation, :plan, :wifi_id, :budget, :image).merge(user_id: current_user.id)
  end

  def set_spot
    @spot = Spot.find(params[:id])
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  def new_guest
    user = User.guest
    sign_in user
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/spots_helper.rb
module SpotsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Jobtora</title>
    <%= favicon_link_tag('favicon jt.ico') %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/spots/_footer.html.erb
<footer>
  <div class="wrapper">
    <p><small>&copy; Jobtora</small></p>
  </div>
</footer>

app/views/spots/_header.html.erb
<header class="page-header wrapper">
  <%= link_to image_tag("logo.jpg", class: :logo), root_path%>
</header>

app/views/spots/_spot.html.erb
<li class="list">
  <%= link_to spot_path(spot.id), method: :get do %>
    <div class="spot-imag-content">
      <%= image_tag spot.image, class:"spot-img" if spot.image.attached? %>
    </div>
    <div class="spot-info">
      <p class="spot-date"><%= spot.name %></p>
      <p class="spot-date"><%= spot.place.name %></p>
      <p class="spot-date"><%= spot.explanation %></p>
    <div>
  <% end %>
</li>

app/views/spots/edit.html.erb
<%= render partial: "header"%>

<div class="container">
  <h2>投稿を編集する</h2>
  <%= form_with(model: @spot, local: true) do |f| %>
    <div class="form-group">
      <%= f.label :name, "スポットの名称" %><br />
      <%= f.text_field :name, class:"input-default", id:"name", placeholder:"例) 〇〇ホテル" %>
    </div>

    <div class="form-group">
      <%= f.label :genre_id, "ジャンル" %><br />
      <%= f.collection_select(:genre_id, Genre.all, :id, :name, {}, {class:"input-default", id:"spot_genre"}) %>
    </div>

    <div class="form-group">
      <%= f.label :place_id, "場所" %><br />
      <%= f.collection_select(:place_id, Place.all, :id, :name, {}, {class:"input-default", id:"spot_place"}) %>
    </div>

    <div class="form-group">
      <%= f.label :explanation, "説明" %><br />
      <%= f.text_area :explanation, class:"input-default", id:"explanation" %>
    </div>

    <div class="form-group">
      <%= f.label :plan, "プラン" %><br />
      <%= f.text_area :plan, class:"input-default", id:"plan", placeholder:"例) 1週間宿泊プラン利用" %>
    </div>

    <div class="form-group">
      <%= f.label :wifi_id, "Wifi(通信環境)" %><br />
      <%= f.collection_select(:wifi_id, Wifi.all, :id, :name, {}, {class:"input-default", id:"spot_wifi"}) %>
    </div>

    <div class="form-group">
      <%= f.label :budget, "予算" %><br />
      <%= f.text_area :budget, class:"input-default", id:"budget", placeholder:"例) 100000" %>
    </div>

    <div class="form-group">
      <div class="file-update">
        <%= f.label :image, "スポットの画像" %><br />
        <%= f.file_field :image %>
      </div>
      <div class="spot__image">
        <%= image_tag @spot.image %>
      </div>
    </div>

    <div class="form-group">
      <%= f.submit "変更する", class: :form__btn  %>
    </div>
  <% end %>
</div>

<%= render partial: "footer"%>

app/views/spots/index.html.erb
<div class="big-bg">
  <header class="page-header wrapper">
    <%= link_to image_tag("logo.jpg", class: :logo), root_path%>
    <nav>
      <%# <ul class="main-nav">
        <li><a href="menu.html">Jobtoraとは?</a></li>
      </ul> %>
    </nav>
    <% if user_signed_in? %>
      <%= link_to "現在のユーザー: #{current_user.nickname}さん", user_path(current_user.id),  method: :get, class: :user__nickname %>
    <% end %>
    <% if user_signed_in? %>
      <div class="login-nav">
        <%= link_to "ログアウト", destroy_user_session_path,  method: :delete, class: :nav__btn %>
        <%= link_to "SPOT投稿", new_spot_path, class: :nav__btn %> 
      </div>
    <% else %> 
      <div class="login-nav">
        <%= link_to 'ゲストログイン(閲覧用)', users_guest_sign_in_path, method: :post, class: :guset__login %>
        <%= link_to "ログイン", new_user_session_path, class: :nav__btn %>
        <%= link_to "新規登録", new_user_registration_path, class: :nav__btn %>
      </div>
    <% end %>
  </header>

  <div class="menu-content wrapper">
    <h3 class="page-title">Jobtoraで新しい働き方探しに行こう</h3>
    <%# <p class="sub-title">
      こんな時代だからこその新しい働き方、こんな状況だからこその楽しみ方見つけて見ない？
    </p> %>
  </div>
</div>

<%# SPOT一覧 %>
<div class="spot-title">
  <h3>NEW SPOT LIST</h3>
</div>
<%= form_with(url: search_spots_path, local: true, method: :get, class: "search-form") do |f| %>
  <%= f.text_field :keyword, placeholder: "施設名を検索する", class: "search-input" %>
  <%= f.submit "検索", class: "search-btn" %>
<% end %>
</div>
<div class="spot-lists">
  <% @spots.each do |spot| %>
    <%= render partial: "spot", locals: { spot: spot } %>
  <% end %>
</div>
<%# SPOT一覧 %>

<%= render partial: "footer" %>

app/views/spots/new.html.erb
<%= render partial: "header" %>

<div class="container">
  <h2>投稿する</h2>
  <%= form_with(model: @spot, local: true) do |f| %>
    <div class="form-group">
      <%= f.label :name, "スポットの名称" %><br />
      <%= f.text_field :name, class:"input-default", id:"name", placeholder:"例) 〇〇ホテル" %>
    </div>

    <div class="form-group">
      <%= f.label :genre_id, "ジャンル" %><br />
      <%= f.collection_select(:genre_id, Genre.all, :id, :name, {}, {class:"input-default", id:"spot_genre"}) %>
    </div>

    <div class="form-group">
      <%= f.label :place_id, "場所" %><br />
      <%= f.collection_select(:place_id, Place.all, :id, :name, {}, {class:"input-default", id:"spot_place"}) %>
    </div>

    <div class="form-group">
      <%= f.label :explanation, "説明" %><br />
      <%= f.text_area :explanation, class:"input-default", id:"explanation" %>
    </div>

    <div class="form-group">
      <%= f.label :plan, "プラン" %><br />
      <%= f.text_area :plan, class:"input-default", id:"plan", placeholder:"例) 1週間宿泊プラン利用" %>
    </div>

    <div class="form-group">
      <%= f.label :wifi_id, "Wifi(通信環境)" %><br />
      <%= f.collection_select(:wifi_id, Wifi.all, :id, :name, {}, {class:"input-default", id:"spot_wifi"}) %>
    </div>

    <div class="form-group">
      <%= f.label :budget, "予算" %><br />
      <%= f.text_area :budget, class:"input-default", id:"budget", placeholder:"例) 100000" %>
    </div>

    <div class="form-group">
      <%= f.label :image, "スポットの画像" %><br />
      <%= f.file_field :images, name: 'spot[images][]', id: 'spot_image' %>
    </div>

    <div class="form-group">
      <%= f.submit "投稿する", class: :form__btn  %>
    </div>
    <div id="image-list"></div>
  <% end %>

  <%= image_tag @spot.image, id: 'image' if @spot.image.present? %>
</div>

<%= render partial: "footer" %>

app/views/spots/search.html.erb
<header class="page-header wrapper">
  <%= link_to image_tag("logo.jpg", class: :logo), root_path%>
  <nav>
    <ul class="main-nav">
      <li><a href="menu.html">Jobtoraとは?</a></li>
    </ul>
  </nav>
  <% if user_signed_in? %>
    <%= link_to "現在のユーザー: #{current_user.nickname}さん", user_path(current_user.id), class: :user__nickname %></li>
  <% end %>
  <% if user_signed_in? %>
    <div class="login-nav">
      <%= link_to "ログアウト", destroy_user_session_path,  method: :delete, class: :nav__btn %>
      <%= link_to "SPOT投稿", new_spot_path, class: :nav__btn %> 
    </div>
  <% else %> 
    <div class="login-nav">
      <%= link_to 'ゲストログイン(閲覧用)', users_guest_sign_in_path, method: :post, class: :guset__login %>
      <%= link_to "ログイン", new_user_session_path, class: :nav__btn %>
      <%= link_to "新規登録", new_user_registration_path, class: :nav__btn %>
    </div>
  <% end %>
</header>

<%# SPOT一覧 %>
<div class="spot-title">
  <h3>SPOT検索一覧</h3>
</div>
<%= form_with(url: search_spots_path, local: true, method: :get, class: "search-form") do |f| %>
  <%= f.text_field :keyword, placeholder: "施設名を検索する", class: "search-input" %>
  <%= f.submit "検索", class: "search-btn" %>
<% end %>
</div>
<div class="spot-lists">
  <% @spots.each do |spot| %>
    <%= render partial: "spot", locals: { spot: spot } %>
  <% end %>
</div>
<%# SPOT一覧 %>

<div class="page__change">
  <%= link_to "トップページへ戻る", root_path %>
</div>

<%= render partial: "footer" %>

app/views/spots/show.html.erb
<%= render partial: "header" %>

<div class="item-show">
  <div class="item-box">
    <h2 class="name">
      <%= @spot.name %>
    </h2>
    <div class='item-img-content'>
      <%= image_tag @spot.image ,class:"item-box-img" %>
    </div>

    <% if current_user == @spot.user %> 
      <%= link_to '編集', edit_spot_path(@spot.id), method: :get, class: "item-red-btn" %>
      <%= link_to '削除', spot_path(@spot.id), method: :delete, class:'item-destroy' %>
    <% end %>

    <table class="detail-table">
      <tbody>
        <tr>
          <th class="detail-item">投稿者</th>
          <td class="detail-value"><%= @spot.user.nickname %></td>
        </tr>
        <tr>
          <th class="detail-item">ジャンル</th>
          <td class="detail-value"><%= @spot.genre.name %></td>
        </tr>
        <tr>
          <th class="detail-item">場所</th>
          <td class="detail-value"><%= @spot.place.name %></td>
        </tr>
        <tr>
          <th class="detail-item">説明</th>
          <td class="detail-value"><%= @spot.explanation %></td>
        </tr>
        <tr>
          <th class="detail-item">プラン</th>
          <td class="detail-value"><%= @spot.plan %></td>
        </tr>
        <tr>
          <th class="detail-item">wifi(通信状況)</th>
          <td class="detail-value"><%= @spot.wifi.name %></td>
        </tr>
        <tr>
          <th class="detail-item">予算</th>
          <td class="detail-value"><%= @spot.budget %></td>
        </tr>
      </tbody>
    </table>
  </div>

  <div class="comment-box">
    <h2>コメント投稿</h2>
    <% if user_signed_in? %>
      <%= form_with(model: [@spot, @comment], local: true) do |f| %>
        <div class="form-group">
          <%= f.label :title, "コメントのタイトル" %><br />
          <%= f.text_field :title, class:"input-default", id:"title" %>
        </div>

        <div class="form-group">
          <%= f.label :genre_id, "評価(星)" %><br />
          <%= f.collection_select(:evaluation_id, Evaluation.all, :id, :name, {}, {class:"input-default", id:"spot_evaluation"}) %>
        </div>

        <div class="form-group">
          <%= f.label :review, "レビューコメント" %><br />
          <%= f.text_area :review, class:"input-default", id:"review" %>
        </div>

        <div class="form-group">
          <%= f.submit "コメントする", class:"comment-btn"  %>
        </div>
      <% end %>
    <% else %>
      <strong><p>※※※ コメントの投稿には新規登録/ログインが必要です ※※※</p></strong>
    <% end %>
  </div>
  <div class="comments">
      <h2>コメント一覧</h2>
      <% @comments.each do |comment| %>
        <p>
          <strong><%= link_to comment.user.nickname, "/users/#{comment.user_id}" %></strong>
          <div class="comment-title">
            <%= comment.title %>
          </div>
          <div class="comment-evaluation">
            <%= "評価#{comment.evaluation.name}" %>
          </div>
          <div class="commment-review">
           <%= comment.review %>
          </div>
        </p>
      <% end %>
    </div>
</div>

<%= render partial: "footer" %>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/show.html.erb
<%= render partial: "spots/header" %>

<div class="mypage-name">
  <h1><%= "#{@user.nickname}さんのマイページ" %></h1>
</div>

<table class="detail-table">
  <tbody>
    <tr>
      <th class="detail-item">ユーザー名</th>
      <td class="detail-value"><%= @user.nickname %></td>
    </tr>
    <tr>
      <th class="detail-item">苗字</th>
      <td class="detail-value"><%= @user.last_name %></td>
    </tr>
    <tr>
      <th class="detail-item">名前</th>
      <td class="detail-value"><%= @user.first_name %></td>
    </tr>
    <tr>
      <th class="detail-item">年齢</th>
      <td class="detail-value"><%= @user.age %></td>
    </tr>
    <tr>
      <th class="detail-item">メールアドレス</th>
      <td class="detail-value"><%= @user.email %></td>
    </tr>
  </tbody>
</table>

<div class="page__change">
  <%= link_to "トップページへ戻る", root_path %>
</div>